// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_content_delivery_bucket": "demotable-host",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "http://demotable-host.s3-website-us-west-2.amazonaws.com"
};


export default awsmobile;
